// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEHr1WqxCpcAB7w75UcH2ggmRbaqIW_vM',
    appId: '1:597145458357:web:c69f81d629669992db50fc',
    messagingSenderId: '597145458357',
    projectId: 'fir-test2-db94e',
    authDomain: 'fir-test2-db94e.firebaseapp.com',
    storageBucket: 'fir-test2-db94e.appspot.com',
    measurementId: 'G-GGSV0RL8ZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXcP1ZcO_PYJaY3apud4IT17GSLgZ7skQ',
    appId: '1:597145458357:android:06a6265a0429c302db50fc',
    messagingSenderId: '597145458357',
    projectId: 'fir-test2-db94e',
    storageBucket: 'fir-test2-db94e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvp9beuv9PyC3Vun1qtYjtR83iMswSAus',
    appId: '1:597145458357:ios:adb6c769eb8b5d5cdb50fc',
    messagingSenderId: '597145458357',
    projectId: 'fir-test2-db94e',
    storageBucket: 'fir-test2-db94e.appspot.com',
    iosBundleId: 'com.example.crudApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvp9beuv9PyC3Vun1qtYjtR83iMswSAus',
    appId: '1:597145458357:ios:0349ea5991c83d19db50fc',
    messagingSenderId: '597145458357',
    projectId: 'fir-test2-db94e',
    storageBucket: 'fir-test2-db94e.appspot.com',
    iosBundleId: 'com.example.crudApp.RunnerTests',
  );
}
